<?php /** @var $this \MvcCore\View */ ?>

<h1><?=$title?></h1>

<p><?=$format(
	'It works! You are using <a href="{0}" target="{1}"><b>{2}</b></a> version: <b><code>"{3}"</code></b>.',
	'https://github.com/mvccore',
	'_blank',
	'MvcCore',
	\MvcCore\Application::VERSION
)?></p>

<p>
	<?php if ($tables): ?>
		Tables founded in database: <b><code>"<?=implode(', ', $tables)?>"</code></b>
	<?php else: ?>
		There was not possible to connect into database. <br />
		<code><?=$errorMsg?></code>
	<?php endif; ?>
</p>
