<?php /** @var $this \MvcCore\View */ ?><!DOCTYPE HTML>
<html lang="en-US">
	<head>
		<meta charset="UTF-8" />
		<title><?php echo $this->Title; ?></title>
		<base href="<?php echo $this->BasePath; ?>/" />
		<link rel="shortcut icon" href="<?php echo $this->BasePath; ?>/static/img/favicon.ico" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=yes" />
		<meta name="apple-mobile-web-app-capable" content="yes" />
		<script>var timestamp=+new Date;(function(a,b,c,d,e,f){if(b[c]('Opera'))b=b[d](e,f);if(b[c]('Trident/'))b=b[d](/ rv:([0-9\.]*)\)/g,e+'$1)');a.setAttribute('data-browser',b);a.className=f;})(document.documentElement,navigator.userAgent,'match','replace',' MSIE ','')</script>
		<?php echo $this->Css('fixedHead')->Render(); ?>
		<?php echo $this->Js('fixedHead')->Render(); ?>
	</head>
	<body>
		<!--[if lt IE 9]><div class="old-browser-warning"><p>Your browser is <b>very</b> old.<br />Please install any actual browser, <br />for example <a href="https://www.google.com/chrome" target="_blank">Google Chrome</a> or <a href="https://www.mozilla.org/en/firefox/new" target="_blank">Mozilla Firefox</a>.</p></div><![endif]-->
			
		<div class="master-container">
			<div class="content">
				<?php echo $this->GetContent(); ?>
			</div>
		</div>
		
	</body>
	<?php echo $this->Js('varFoot')->Render(); ?>
</html>
