<?php /** @var $this MvcCore_View */ ?><!DOCTYPE HTML>
<html lang="en-US">
	<head>
		<meta charset="UTF-8" />
		<title><?php echo $this->Title; ?></title>
		
		<?php /* force render mode in newest IE, strictly do not use any back compatibility modes in MSIE browsers for this page */ ?>
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes" />
		<meta name="apple-mobile-web-app-capable" content="yes" />
		
		<link rel="shortcut icon" href="static/img/favicon.ico" />
		<link rel="stylesheet" href="static/css/fonts.css" media="all" />
		<link rel="stylesheet" href="static/css/all.css" media="all" />
		
		<script type="text/javascript" src="static/js/libs/class.min.js"></script>
		<script type="text/javascript" src="static/js/libs/ajax.min.js"></script>
		<script type="text/javascript" src="static/js/libs/Module.js"></script>
	</head>
	<body>
	
		<!--[if lt IE 9]><div class="filters"><![endif]-->
		<!--[if (gt IE 8)|!(IE)]><!--><div class="no-filters">
			<!--<![endif]-->
			
			<div class="master-container">
				<div class="content">
				
					<?php echo $this->GetContent(); ?>
					
				</div>
			</div>
			
		</div>
		
	</body>
	
	<script type="text/javascript" src="static/js/Front.js"></script>
	
</html>